// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZxHoRSjTryaIXGWzqzr6zfR2GvJdwWfk',
    appId: '1:1063306793581:web:5bf2dfb0cf0ef7dc786564',
    messagingSenderId: '1063306793581',
    projectId: 'eventpass-bdc7d',
    authDomain: 'eventpass-bdc7d.firebaseapp.com',
    storageBucket: 'eventpass-bdc7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7lm_02Npw3jYqG72iT69-3kxML26ZvkQ',
    appId: '1:1063306793581:android:6b853b7178a01cd2786564',
    messagingSenderId: '1063306793581',
    projectId: 'eventpass-bdc7d',
    storageBucket: 'eventpass-bdc7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkGjgK4wquZTPYzkhrSd4BYSMok3UxDvQ',
    appId: '1:1063306793581:ios:6feac51ea2f87809786564',
    messagingSenderId: '1063306793581',
    projectId: 'eventpass-bdc7d',
    storageBucket: 'eventpass-bdc7d.firebasestorage.app',
    iosBundleId: 'com.eventos.asistenciaEventos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkGjgK4wquZTPYzkhrSd4BYSMok3UxDvQ',
    appId: '1:1063306793581:ios:6feac51ea2f87809786564',
    messagingSenderId: '1063306793581',
    projectId: 'eventpass-bdc7d',
    storageBucket: 'eventpass-bdc7d.firebasestorage.app',
    iosBundleId: 'com.eventos.asistenciaEventos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZxHoRSjTryaIXGWzqzr6zfR2GvJdwWfk',
    appId: '1:1063306793581:web:c324352fff97bea8786564',
    messagingSenderId: '1063306793581',
    projectId: 'eventpass-bdc7d',
    authDomain: 'eventpass-bdc7d.firebaseapp.com',
    storageBucket: 'eventpass-bdc7d.firebasestorage.app',
  );
}
